/**
 * @copyright
 * (c) 2025 netTrek GmbH & Co. KG – All rights reserved.
 *
 * This source code is part of the C2PA-HLS integration library.
 */

// wasm-url-literal.plugin.mjs
//
// PURPOSE
// -------
// esbuilds default loader for ".wasm" converts an import like
//
//    import wasm from "pkg/dist/file.wasm";
//
// into
//
//    var wasm_default = "./assets/file-XYZ.wasm";
//    ...
//    new URL(wasm_default, import.meta.url);
//
// i.e. the URL is constructed from a **variable**, not a **literal**.
// That breaks static analysis in other bundlers (webpack/vite/rollup)
// when **this built library** is consumed downstream.
//
// Why is that a problem?
// ----------------------
// Webpack (and similar bundlers) only emit/copy assets when it can
// statically detect *literal string references* to the file path,
// e.g. new URL("./resources/file.wasm", import.meta.url)
//
// But once esbuild has already turned the wasm import into a **variable**,
// webpack cannot see the real file anymore -> it does NOT copy the .wasm,
// so consumers get 404 or inline fallback.
//
// WHAT THIS PLUGIN DOES
// ----------------------
// - It resolves the WASM file via Node/npm resolution (also works with scoped pkgs).
// - It copies the actual file into your dist/resources folder (like a bundler would).
// - It replaces the imported module with a JS module that exports a **literal**
//
//       export default new URL("./resources/file.wasm", import.meta.url).toString();
//
// This keeps your published ESM consumable by webpack/vite:
// - Webpack CAN now "see" the wasm reference again and will emit/copy it correctly.
// - No base64 inlining.
// - No missing wasm at runtime.
// - No special config required in the consumer.
//

import {createRequire} from "node:module";
import {mkdirSync, copyFileSync} from "node:fs";
import {dirname, basename, join} from "node:path";

export default function wasmUrlLiteralPlugin(userOpts = {}) {
    const require = createRequire(import.meta.url);

    // Defaults; outDir will be taken from esbuild if set
    const defaults = {
        outSub: "resources", // subfolder under outdir where wasm is copied
    };

    const opts = {...defaults, ...userOpts};

    return {
        name: "wasm-url-literal",
        setup(build) {
            // Prefer esbuild's configured outdir if present
            const outDir = build.initialOptions.outdir || userOpts.outDir || "dist";

            // 1) Resolve .wasm with proper Node/npm resolution (scoped pkgs etc.)
            build.onResolve({filter: /\.wasm$/}, (args) => {
                try {
                    const resolved = require.resolve(args.path, {paths: [args.resolveDir]});
                    return {
                        path: resolved,
                        namespace: "wasm-url",
                        pluginData: {
                            sourceImport: args.path,
                        },
                    };
                } catch (e) {
                    // Let esbuild fall back to its resolver if resolve fails
                    return null;
                }
            });

            // 2) Copy file into outdir/resources and emit a JS module with a literal URL
            build.onLoad({
                filter: /.*/,
                namespace: "wasm-url"
            }, (args) => {
                const fileName = basename(args.path);
                const relOut = `${opts.outSub}/${fileName}`; // e.g. resources/c2pa_bg.wasm
                const absOut = join(outDir, relOut);

                mkdirSync(dirname(absOut), {recursive: true});
                copyFileSync(args.path, absOut);

                // Always POSIX style for URLs
                const relOutPosix = relOut.replace(/\\/g, "/");

                const js = `// generated by wasm-url-literal plugin
const url = new URL("./${relOutPosix}", import.meta.url).toString();
export default url;
`;

                return {
                    contents: js,
                    loader: "js",
                    watchFiles: [args.path], // watch the source wasm in --watch
                };
            });
        },
    };
}
